export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_RECIPE = "GET_RECIPE";
export const GET_RECIPE_REQUEST = "GET_RECIPE_REQUEST";
